// <auto-generated />
namespace JobSearchTracker.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Address_has_Required_FK_PersonId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Address_has_Required_FK_PersonId));
        
        string IMigrationMetadata.Id
        {
            get { return "201709071453176_Address_has_Required_FK_PersonId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
