// <auto-generated />
namespace JobSearchTracker.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class JobLead_Has_Person : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JobLead_Has_Person));
        
        string IMigrationMetadata.Id
        {
            get { return "201709051744037_JobLead_Has_Person"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
