// <auto-generated />
namespace JobSearchTracker.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class current : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(current));
        
        string IMigrationMetadata.Id
        {
            get { return "201709071327134_current"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
